// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../';
import DodoPayments from 'dodopayments';

export const metadata: Metadata = {
  resource: 'subscriptions',
  operation: 'write',
  tags: [],
};

export const tool: Tool = {
  name: 'update_subscriptions',
  description: '',
  inputSchema: {
    type: 'object',
    properties: {
      subscription_id: {
        type: 'string',
      },
      billing: {
        type: 'object',
        properties: {
          city: {
            type: 'string',
            description: 'City name',
          },
          country: {
            type: 'string',
            description: 'ISO country code alpha2 variant',
            enum: [
              'AF',
              'AX',
              'AL',
              'DZ',
              'AS',
              'AD',
              'AO',
              'AI',
              'AQ',
              'AG',
              'AR',
              'AM',
              'AW',
              'AU',
              'AT',
              'AZ',
              'BS',
              'BH',
              'BD',
              'BB',
              'BY',
              'BE',
              'BZ',
              'BJ',
              'BM',
              'BT',
              'BO',
              'BQ',
              'BA',
              'BW',
              'BV',
              'BR',
              'IO',
              'BN',
              'BG',
              'BF',
              'BI',
              'KH',
              'CM',
              'CA',
              'CV',
              'KY',
              'CF',
              'TD',
              'CL',
              'CN',
              'CX',
              'CC',
              'CO',
              'KM',
              'CG',
              'CD',
              'CK',
              'CR',
              'CI',
              'HR',
              'CU',
              'CW',
              'CY',
              'CZ',
              'DK',
              'DJ',
              'DM',
              'DO',
              'EC',
              'EG',
              'SV',
              'GQ',
              'ER',
              'EE',
              'ET',
              'FK',
              'FO',
              'FJ',
              'FI',
              'FR',
              'GF',
              'PF',
              'TF',
              'GA',
              'GM',
              'GE',
              'DE',
              'GH',
              'GI',
              'GR',
              'GL',
              'GD',
              'GP',
              'GU',
              'GT',
              'GG',
              'GN',
              'GW',
              'GY',
              'HT',
              'HM',
              'VA',
              'HN',
              'HK',
              'HU',
              'IS',
              'IN',
              'ID',
              'IR',
              'IQ',
              'IE',
              'IM',
              'IL',
              'IT',
              'JM',
              'JP',
              'JE',
              'JO',
              'KZ',
              'KE',
              'KI',
              'KP',
              'KR',
              'KW',
              'KG',
              'LA',
              'LV',
              'LB',
              'LS',
              'LR',
              'LY',
              'LI',
              'LT',
              'LU',
              'MO',
              'MK',
              'MG',
              'MW',
              'MY',
              'MV',
              'ML',
              'MT',
              'MH',
              'MQ',
              'MR',
              'MU',
              'YT',
              'MX',
              'FM',
              'MD',
              'MC',
              'MN',
              'ME',
              'MS',
              'MA',
              'MZ',
              'MM',
              'NA',
              'NR',
              'NP',
              'NL',
              'NC',
              'NZ',
              'NI',
              'NE',
              'NG',
              'NU',
              'NF',
              'MP',
              'NO',
              'OM',
              'PK',
              'PW',
              'PS',
              'PA',
              'PG',
              'PY',
              'PE',
              'PH',
              'PN',
              'PL',
              'PT',
              'PR',
              'QA',
              'RE',
              'RO',
              'RU',
              'RW',
              'BL',
              'SH',
              'KN',
              'LC',
              'MF',
              'PM',
              'VC',
              'WS',
              'SM',
              'ST',
              'SA',
              'SN',
              'RS',
              'SC',
              'SL',
              'SG',
              'SX',
              'SK',
              'SI',
              'SB',
              'SO',
              'ZA',
              'GS',
              'SS',
              'ES',
              'LK',
              'SD',
              'SR',
              'SJ',
              'SZ',
              'SE',
              'CH',
              'SY',
              'TW',
              'TJ',
              'TZ',
              'TH',
              'TL',
              'TG',
              'TK',
              'TO',
              'TT',
              'TN',
              'TR',
              'TM',
              'TC',
              'TV',
              'UG',
              'UA',
              'AE',
              'GB',
              'UM',
              'US',
              'UY',
              'UZ',
              'VU',
              'VE',
              'VN',
              'VG',
              'VI',
              'WF',
              'EH',
              'YE',
              'ZM',
              'ZW',
            ],
          },
          state: {
            type: 'string',
            description: 'State or province name',
          },
          street: {
            type: 'string',
            description: 'Street address including house number and unit/apartment if applicable',
          },
          zipcode: {
            type: 'string',
            description: 'Postal code or ZIP code',
          },
        },
        required: ['city', 'country', 'state', 'street', 'zipcode'],
      },
      metadata: {
        type: 'object',
      },
      status: {
        type: 'string',
        enum: ['pending', 'active', 'on_hold', 'paused', 'cancelled', 'failed', 'expired'],
      },
      tax_id: {
        type: 'string',
      },
    },
  },
};

export const handler = (client: DodoPayments, args: any) => {
  const { subscription_id, ...body } = args;
  return client.subscriptions.update(subscription_id, body);
};

export default { metadata, tool, handler };
